session_name: Earth Rovers ROS2 Container
windows:
  - window_name: Earth Rovers Core Nodes
    layout: tiled
    shell_command_before:
      - bash
      - cd /earthrovers_ws
      - source /opt/ros/humble/setup.bash
      - source install/local_setup.bash
    panes:
    - shell_command:
      - ros2 run earthrovers_base base --ros-args --log-level debug
    - shell_command:
      - ros2 run earthrovers_navigation nav
    - shell_command:
      - ros2 run earthrovers_vision cameras
    - shell_command:
      - ros2 run teleop_twist_keyboard teleop_twist_keyboard
    - shell_command:
      - ros2 run rviz2 rviz2 -d src/earthrovers_viz/rviz/rover_config.rviz
options:
  mouse: on  # Enable mouse mode