# Service for returning a list of checkpoints expressed in the GPS world frame.
# TODO: Need to figure out if it makes more sense to return the list of
# checkpoints in the GPS world frame or an inertial frame like odom.  
---
geometry_msgs/PoseStamped[] checkpoints
uint32 latest_scanned_checkpoint_index